/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.luminesce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The method of name/type column inference being used
 */
@JsonAdapter(AutoDetectType.Adapter.class)
public enum AutoDetectType {
  
  AUTO("Auto"),
  
  SPECIFYCOLUMNSYETINFERTYPES("SpecifyColumnsYetInferTypes"),
  
  SPECIFYCOLUMNSANDTYPES("SpecifyColumnsAndTypes");

  private String value;

  AutoDetectType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AutoDetectType fromValue(String value) {
    for (AutoDetectType b : AutoDetectType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AutoDetectType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AutoDetectType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AutoDetectType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AutoDetectType.fromValue(value);
    }
  }
}

