/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.luminesce.model;

import java.util.Objects;
import com.finbourne.luminesce.model.BackgroundQueryState;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.luminesce.JSON;

/**
 * A background query the calling user currently has available to them
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BackgroundQueryListItem {
  public static final String SERIALIZED_NAME_EXECUTION_ID = "executionId";
  @SerializedName(SERIALIZED_NAME_EXECUTION_ID)
  private String executionId;

  public static final String SERIALIZED_NAME_QUERY = "query";
  @SerializedName(SERIALIZED_NAME_QUERY)
  private String query;

  public static final String SERIALIZED_NAME_QUERY_NAME = "queryName";
  @SerializedName(SERIALIZED_NAME_QUERY_NAME)
  private String queryName;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private BackgroundQueryState state;

  public static final String SERIALIZED_NAME_WHEN = "when";
  @SerializedName(SERIALIZED_NAME_WHEN)
  private OffsetDateTime when;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expiresAt";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  private OffsetDateTime expiresAt;

  public BackgroundQueryListItem() {
  }

  public BackgroundQueryListItem executionId(String executionId) {
    
    this.executionId = executionId;
    return this;
  }

   /**
   * ExecutionId of the query
   * @return executionId
  **/
  @jakarta.annotation.Nullable
  public String getExecutionId() {
    return executionId;
  }


  public void setExecutionId(String executionId) {
    this.executionId = executionId;
  }


  public BackgroundQueryListItem query(String query) {
    
    this.query = query;
    return this;
  }

   /**
   * The LuminesceSql of the original request
   * @return query
  **/
  @jakarta.annotation.Nullable
  public String getQuery() {
    return query;
  }


  public void setQuery(String query) {
    this.query = query;
  }


  public BackgroundQueryListItem queryName(String queryName) {
    
    this.queryName = queryName;
    return this;
  }

   /**
   * The QueryName given in the original request
   * @return queryName
  **/
  @jakarta.annotation.Nullable
  public String getQueryName() {
    return queryName;
  }


  public void setQueryName(String queryName) {
    this.queryName = queryName;
  }


  public BackgroundQueryListItem state(BackgroundQueryState state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @jakarta.annotation.Nullable
  public BackgroundQueryState getState() {
    return state;
  }


  public void setState(BackgroundQueryState state) {
    this.state = state;
  }


  public BackgroundQueryListItem when(OffsetDateTime when) {
    
    this.when = when;
    return this;
  }

   /**
   * When the state of this query (and so its data) was last updated (UTC)
   * @return when
  **/
  @jakarta.annotation.Nullable
  public OffsetDateTime getWhen() {
    return when;
  }


  public void setWhen(OffsetDateTime when) {
    this.when = when;
  }


  public BackgroundQueryListItem expiresAt(OffsetDateTime expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * When the query (and its data) may be removed (UTC)
   * @return expiresAt
  **/
  @jakarta.annotation.Nullable
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }


  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackgroundQueryListItem backgroundQueryListItem = (BackgroundQueryListItem) o;
    return Objects.equals(this.executionId, backgroundQueryListItem.executionId) &&
        Objects.equals(this.query, backgroundQueryListItem.query) &&
        Objects.equals(this.queryName, backgroundQueryListItem.queryName) &&
        Objects.equals(this.state, backgroundQueryListItem.state) &&
        Objects.equals(this.when, backgroundQueryListItem.when) &&
        Objects.equals(this.expiresAt, backgroundQueryListItem.expiresAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(executionId, query, queryName, state, when, expiresAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackgroundQueryListItem {\n");
    sb.append("    executionId: ").append(toIndentedString(executionId)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    queryName: ").append(toIndentedString(queryName)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    when: ").append(toIndentedString(when)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("executionId");
    openapiFields.add("query");
    openapiFields.add("queryName");
    openapiFields.add("state");
    openapiFields.add("when");
    openapiFields.add("expiresAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BackgroundQueryListItem
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BackgroundQueryListItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BackgroundQueryListItem is not found in the empty JSON string", BackgroundQueryListItem.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("executionId") != null && !jsonObj.get("executionId").isJsonNull()) && !jsonObj.get("executionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `executionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("executionId").toString()));
      }
      if ((jsonObj.get("query") != null && !jsonObj.get("query").isJsonNull()) && !jsonObj.get("query").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `query` to be a primitive type in the JSON string but got `%s`", jsonObj.get("query").toString()));
      }
      if ((jsonObj.get("queryName") != null && !jsonObj.get("queryName").isJsonNull()) && !jsonObj.get("queryName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `queryName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("queryName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BackgroundQueryListItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BackgroundQueryListItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BackgroundQueryListItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BackgroundQueryListItem.class));

       return (TypeAdapter<T>) new TypeAdapter<BackgroundQueryListItem>() {
           @Override
           public void write(JsonWriter out, BackgroundQueryListItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BackgroundQueryListItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BackgroundQueryListItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BackgroundQueryListItem
  * @throws IOException if the JSON string is invalid with respect to BackgroundQueryListItem
  */
  public static BackgroundQueryListItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BackgroundQueryListItem.class);
  }

 /**
  * Convert an instance of BackgroundQueryListItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
