/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.luminesce.model;

import java.util.Objects;
import com.finbourne.luminesce.model.CaseStatementItem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.luminesce.JSON;

/**
 * Representation of the selected field and a list of: filter, source, and target.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CaseStatementDesign {
  public static final String SERIALIZED_NAME_SELECTED_FIELD = "selectedField";
  @SerializedName(SERIALIZED_NAME_SELECTED_FIELD)
  private String selectedField;

  public static final String SERIALIZED_NAME_CASE_STATEMENT_ITEMS = "caseStatementItems";
  @SerializedName(SERIALIZED_NAME_CASE_STATEMENT_ITEMS)
  private List<CaseStatementItem> caseStatementItems;

  public CaseStatementDesign() {
  }

  public CaseStatementDesign selectedField(String selectedField) {
    
    this.selectedField = selectedField;
    return this;
  }

   /**
   * Selected field in the SQL query.
   * @return selectedField
  **/
  @jakarta.annotation.Nullable
  public String getSelectedField() {
    return selectedField;
  }


  public void setSelectedField(String selectedField) {
    this.selectedField = selectedField;
  }


  public CaseStatementDesign caseStatementItems(List<CaseStatementItem> caseStatementItems) {
    
    this.caseStatementItems = caseStatementItems;
    return this;
  }

  public CaseStatementDesign addCaseStatementItemsItem(CaseStatementItem caseStatementItemsItem) {
    if (this.caseStatementItems == null) {
      this.caseStatementItems = new ArrayList<>();
    }
    this.caseStatementItems.add(caseStatementItemsItem);
    return this;
  }

   /**
   * A list containing the filter, source, and target.
   * @return caseStatementItems
  **/
  @jakarta.annotation.Nullable
  public List<CaseStatementItem> getCaseStatementItems() {
    return caseStatementItems;
  }


  public void setCaseStatementItems(List<CaseStatementItem> caseStatementItems) {
    this.caseStatementItems = caseStatementItems;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseStatementDesign caseStatementDesign = (CaseStatementDesign) o;
    return Objects.equals(this.selectedField, caseStatementDesign.selectedField) &&
        Objects.equals(this.caseStatementItems, caseStatementDesign.caseStatementItems);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(selectedField, caseStatementItems);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseStatementDesign {\n");
    sb.append("    selectedField: ").append(toIndentedString(selectedField)).append("\n");
    sb.append("    caseStatementItems: ").append(toIndentedString(caseStatementItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("selectedField");
    openapiFields.add("caseStatementItems");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CaseStatementDesign
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CaseStatementDesign.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CaseStatementDesign is not found in the empty JSON string", CaseStatementDesign.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("selectedField") != null && !jsonObj.get("selectedField").isJsonNull()) && !jsonObj.get("selectedField").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `selectedField` to be a primitive type in the JSON string but got `%s`", jsonObj.get("selectedField").toString()));
      }
      if (jsonObj.get("caseStatementItems") != null && !jsonObj.get("caseStatementItems").isJsonNull()) {
        JsonArray jsonArraycaseStatementItems = jsonObj.getAsJsonArray("caseStatementItems");
        if (jsonArraycaseStatementItems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("caseStatementItems").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `caseStatementItems` to be an array in the JSON string but got `%s`", jsonObj.get("caseStatementItems").toString()));
          }

          // validate the optional field `caseStatementItems` (array)
          for (int i = 0; i < jsonArraycaseStatementItems.size(); i++) {
            CaseStatementItem.validateJsonElement(jsonArraycaseStatementItems.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CaseStatementDesign.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CaseStatementDesign' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CaseStatementDesign> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CaseStatementDesign.class));

       return (TypeAdapter<T>) new TypeAdapter<CaseStatementDesign>() {
           @Override
           public void write(JsonWriter out, CaseStatementDesign value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CaseStatementDesign read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CaseStatementDesign given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CaseStatementDesign
  * @throws IOException if the JSON string is invalid with respect to CaseStatementDesign
  */
  public static CaseStatementDesign fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CaseStatementDesign.class);
  }

 /**
  * Convert an instance of CaseStatementDesign to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
