/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.luminesce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of the certificate file to be downloaded (both public and private are needed to connect)
 */
@JsonAdapter(CertificateFileType.Adapter.class)
public enum CertificateFileType {
  
  PUBLIC("Public"),
  
  PRIVATE("Private");

  private String value;

  CertificateFileType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CertificateFileType fromValue(String value) {
    for (CertificateFileType b : CertificateFileType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CertificateFileType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CertificateFileType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CertificateFileType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CertificateFileType.fromValue(value);
    }
  }
}

