/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.luminesce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets IntellisenseType
 */
@JsonAdapter(IntellisenseType.Adapter.class)
public enum IntellisenseType {
  
  KEYWORD("Keyword"),
  
  SYMBOL("Symbol"),
  
  FUNCTION("Function"),
  
  OPERATOR("Operator"),
  
  TABLE("Table"),
  
  COLUMN("Column"),
  
  PARAMETER("Parameter"),
  
  SCALARVARIABLE("ScalarVariable");

  private String value;

  IntellisenseType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static IntellisenseType fromValue(String value) {
    for (IntellisenseType b : IntellisenseType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<IntellisenseType> {
    @Override
    public void write(final JsonWriter jsonWriter, final IntellisenseType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public IntellisenseType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return IntellisenseType.fromValue(value);
    }
  }
}

