/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.luminesce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.luminesce.JSON;

/**
 * Lineage
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Lineage {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_SUBTYPE = "subtype";
  @SerializedName(SERIALIZED_NAME_SUBTYPE)
  private String subtype;

  public static final String SERIALIZED_NAME_ALIAS = "alias";
  @SerializedName(SERIALIZED_NAME_ALIAS)
  private String alias;

  public static final String SERIALIZED_NAME_COLUMN_TITLE_TOOLTIP = "columnTitleTooltip";
  @SerializedName(SERIALIZED_NAME_COLUMN_TITLE_TOOLTIP)
  private String columnTitleTooltip;

  public static final String SERIALIZED_NAME_EXPLAIN_TITLE = "explainTitle";
  @SerializedName(SERIALIZED_NAME_EXPLAIN_TITLE)
  private String explainTitle;

  public static final String SERIALIZED_NAME_EXPLAIN_TOOLTIP = "explainTooltip";
  @SerializedName(SERIALIZED_NAME_EXPLAIN_TOOLTIP)
  private String explainTooltip;

  public static final String SERIALIZED_NAME_FULL_FORMULA = "fullFormula";
  @SerializedName(SERIALIZED_NAME_FULL_FORMULA)
  private String fullFormula;

  public static final String SERIALIZED_NAME_DOCUMENTATION_AS_HTML = "documentationAsHtml";
  @SerializedName(SERIALIZED_NAME_DOCUMENTATION_AS_HTML)
  private String documentationAsHtml;

  public static final String SERIALIZED_NAME_DOCUMENTATION_AS_MARK_DOWN = "documentationAsMarkDown";
  @SerializedName(SERIALIZED_NAME_DOCUMENTATION_AS_MARK_DOWN)
  private String documentationAsMarkDown;

  public static final String SERIALIZED_NAME_CHILDREN = "children";
  @SerializedName(SERIALIZED_NAME_CHILDREN)
  private List<Lineage> children;

  public Lineage() {
  }

  public Lineage type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nullable
  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public Lineage subtype(String subtype) {
    
    this.subtype = subtype;
    return this;
  }

   /**
   * Get subtype
   * @return subtype
  **/
  @jakarta.annotation.Nullable
  public String getSubtype() {
    return subtype;
  }


  public void setSubtype(String subtype) {
    this.subtype = subtype;
  }


  public Lineage alias(String alias) {
    
    this.alias = alias;
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  @jakarta.annotation.Nullable
  public String getAlias() {
    return alias;
  }


  public void setAlias(String alias) {
    this.alias = alias;
  }


  public Lineage columnTitleTooltip(String columnTitleTooltip) {
    
    this.columnTitleTooltip = columnTitleTooltip;
    return this;
  }

   /**
   * Get columnTitleTooltip
   * @return columnTitleTooltip
  **/
  @jakarta.annotation.Nullable
  public String getColumnTitleTooltip() {
    return columnTitleTooltip;
  }


  public void setColumnTitleTooltip(String columnTitleTooltip) {
    this.columnTitleTooltip = columnTitleTooltip;
  }


  public Lineage explainTitle(String explainTitle) {
    
    this.explainTitle = explainTitle;
    return this;
  }

   /**
   * Get explainTitle
   * @return explainTitle
  **/
  @jakarta.annotation.Nullable
  public String getExplainTitle() {
    return explainTitle;
  }


  public void setExplainTitle(String explainTitle) {
    this.explainTitle = explainTitle;
  }


  public Lineage explainTooltip(String explainTooltip) {
    
    this.explainTooltip = explainTooltip;
    return this;
  }

   /**
   * Get explainTooltip
   * @return explainTooltip
  **/
  @jakarta.annotation.Nullable
  public String getExplainTooltip() {
    return explainTooltip;
  }


  public void setExplainTooltip(String explainTooltip) {
    this.explainTooltip = explainTooltip;
  }


  public Lineage fullFormula(String fullFormula) {
    
    this.fullFormula = fullFormula;
    return this;
  }

   /**
   * Get fullFormula
   * @return fullFormula
  **/
  @jakarta.annotation.Nullable
  public String getFullFormula() {
    return fullFormula;
  }


  public void setFullFormula(String fullFormula) {
    this.fullFormula = fullFormula;
  }


  public Lineage documentationAsHtml(String documentationAsHtml) {
    
    this.documentationAsHtml = documentationAsHtml;
    return this;
  }

   /**
   * Get documentationAsHtml
   * @return documentationAsHtml
  **/
  @jakarta.annotation.Nullable
  public String getDocumentationAsHtml() {
    return documentationAsHtml;
  }


  public void setDocumentationAsHtml(String documentationAsHtml) {
    this.documentationAsHtml = documentationAsHtml;
  }


  public Lineage documentationAsMarkDown(String documentationAsMarkDown) {
    
    this.documentationAsMarkDown = documentationAsMarkDown;
    return this;
  }

   /**
   * Get documentationAsMarkDown
   * @return documentationAsMarkDown
  **/
  @jakarta.annotation.Nullable
  public String getDocumentationAsMarkDown() {
    return documentationAsMarkDown;
  }


  public void setDocumentationAsMarkDown(String documentationAsMarkDown) {
    this.documentationAsMarkDown = documentationAsMarkDown;
  }


  public Lineage children(List<Lineage> children) {
    
    this.children = children;
    return this;
  }

  public Lineage addChildrenItem(Lineage childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @jakarta.annotation.Nullable
  public List<Lineage> getChildren() {
    return children;
  }


  public void setChildren(List<Lineage> children) {
    this.children = children;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Lineage lineage = (Lineage) o;
    return Objects.equals(this.type, lineage.type) &&
        Objects.equals(this.subtype, lineage.subtype) &&
        Objects.equals(this.alias, lineage.alias) &&
        Objects.equals(this.columnTitleTooltip, lineage.columnTitleTooltip) &&
        Objects.equals(this.explainTitle, lineage.explainTitle) &&
        Objects.equals(this.explainTooltip, lineage.explainTooltip) &&
        Objects.equals(this.fullFormula, lineage.fullFormula) &&
        Objects.equals(this.documentationAsHtml, lineage.documentationAsHtml) &&
        Objects.equals(this.documentationAsMarkDown, lineage.documentationAsMarkDown) &&
        Objects.equals(this.children, lineage.children);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, subtype, alias, columnTitleTooltip, explainTitle, explainTooltip, fullFormula, documentationAsHtml, documentationAsMarkDown, children);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Lineage {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    subtype: ").append(toIndentedString(subtype)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    columnTitleTooltip: ").append(toIndentedString(columnTitleTooltip)).append("\n");
    sb.append("    explainTitle: ").append(toIndentedString(explainTitle)).append("\n");
    sb.append("    explainTooltip: ").append(toIndentedString(explainTooltip)).append("\n");
    sb.append("    fullFormula: ").append(toIndentedString(fullFormula)).append("\n");
    sb.append("    documentationAsHtml: ").append(toIndentedString(documentationAsHtml)).append("\n");
    sb.append("    documentationAsMarkDown: ").append(toIndentedString(documentationAsMarkDown)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("subtype");
    openapiFields.add("alias");
    openapiFields.add("columnTitleTooltip");
    openapiFields.add("explainTitle");
    openapiFields.add("explainTooltip");
    openapiFields.add("fullFormula");
    openapiFields.add("documentationAsHtml");
    openapiFields.add("documentationAsMarkDown");
    openapiFields.add("children");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Lineage
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Lineage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Lineage is not found in the empty JSON string", Lineage.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("subtype") != null && !jsonObj.get("subtype").isJsonNull()) && !jsonObj.get("subtype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subtype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subtype").toString()));
      }
      if ((jsonObj.get("alias") != null && !jsonObj.get("alias").isJsonNull()) && !jsonObj.get("alias").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `alias` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alias").toString()));
      }
      if ((jsonObj.get("columnTitleTooltip") != null && !jsonObj.get("columnTitleTooltip").isJsonNull()) && !jsonObj.get("columnTitleTooltip").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `columnTitleTooltip` to be a primitive type in the JSON string but got `%s`", jsonObj.get("columnTitleTooltip").toString()));
      }
      if ((jsonObj.get("explainTitle") != null && !jsonObj.get("explainTitle").isJsonNull()) && !jsonObj.get("explainTitle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `explainTitle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("explainTitle").toString()));
      }
      if ((jsonObj.get("explainTooltip") != null && !jsonObj.get("explainTooltip").isJsonNull()) && !jsonObj.get("explainTooltip").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `explainTooltip` to be a primitive type in the JSON string but got `%s`", jsonObj.get("explainTooltip").toString()));
      }
      if ((jsonObj.get("fullFormula") != null && !jsonObj.get("fullFormula").isJsonNull()) && !jsonObj.get("fullFormula").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fullFormula` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fullFormula").toString()));
      }
      if ((jsonObj.get("documentationAsHtml") != null && !jsonObj.get("documentationAsHtml").isJsonNull()) && !jsonObj.get("documentationAsHtml").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentationAsHtml` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentationAsHtml").toString()));
      }
      if ((jsonObj.get("documentationAsMarkDown") != null && !jsonObj.get("documentationAsMarkDown").isJsonNull()) && !jsonObj.get("documentationAsMarkDown").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentationAsMarkDown` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentationAsMarkDown").toString()));
      }
      if (jsonObj.get("children") != null && !jsonObj.get("children").isJsonNull()) {
        JsonArray jsonArraychildren = jsonObj.getAsJsonArray("children");
        if (jsonArraychildren != null) {
          // ensure the json data is an array
          if (!jsonObj.get("children").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `children` to be an array in the JSON string but got `%s`", jsonObj.get("children").toString()));
          }

          // validate the optional field `children` (array)
          for (int i = 0; i < jsonArraychildren.size(); i++) {
            Lineage.validateJsonElement(jsonArraychildren.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Lineage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Lineage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Lineage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Lineage.class));

       return (TypeAdapter<T>) new TypeAdapter<Lineage>() {
           @Override
           public void write(JsonWriter out, Lineage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Lineage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Lineage given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Lineage
  * @throws IOException if the JSON string is invalid with respect to Lineage
  */
  public static Lineage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Lineage.class);
  }

 /**
  * Convert an instance of Lineage to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
