/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.luminesce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets LineageColumnIcon
 */
@JsonAdapter(LineageColumnIcon.Adapter.class)
public enum LineageColumnIcon {
  
  NONE("None"),
  
  CALCULATION("Calculation"),
  
  AGGREGATION("Aggregation"),
  
  DERIVEDPROPERTY("DerivedProperty");

  private String value;

  LineageColumnIcon(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LineageColumnIcon fromValue(String value) {
    for (LineageColumnIcon b : LineageColumnIcon.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<LineageColumnIcon> {
    @Override
    public void write(final JsonWriter jsonWriter, final LineageColumnIcon enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LineageColumnIcon read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LineageColumnIcon.fromValue(value);
    }
  }
}

