/*
 * FINBOURNE Luminesce Web API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.luminesce.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Direction of Order By terms in the Order By clause
 */
@JsonAdapter(OrderByDirection.Adapter.class)
public enum OrderByDirection {
  
  ASC("asc"),
  
  DESC("desc");

  private String value;

  OrderByDirection(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OrderByDirection fromValue(String value) {
    for (OrderByDirection b : OrderByDirection.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OrderByDirection> {
    @Override
    public void write(final JsonWriter jsonWriter, final OrderByDirection enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OrderByDirection read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OrderByDirection.fromValue(value);
    }
  }
}

